-- Schema and dev data are owned by EF Core migrations (DEV-150+) and runtime seed (DEV-152).
-- This file is no longer mounted into Postgres init — see docker-compose.yml and docs/DEV_COMMANDS.md.
--
-- Local flow after `docker compose up -d db`:
--   cd backend && dotnet ef database update --project OnlinePortfolio.Api
-- DEV-152 will add Starter plan + tenants ana/joao via API seed.
